### ISSUE TITLE
Longitud de la traducción de Channels a Redistribuir

### ISSUE THREAD

**Issue by pplurueda** [WallaceMcGregor/bob-translation-es#1]
![image](https://user-images.githubusercontent.com/82481289/224428370-f6aec920-080d-4cf3-9c86-1c40595e7d02.png)
No permite pulsar el pequeño botón rojo para resetear los usos.

**Comment by WallaceMcGregor** [comment]
Es un problema del diseño del sistema original, que no se ajusta el tamaño de todas estas cosas al texto. Ya se ha informado al autor del mismo, así que solo queda esperar para que lo solucione.

**Comment by WallaceMcGregor** [comment]
> ![image](https://user-images.githubusercontent.com/82481289/224428370-f6aec920-080d-4cf3-9c86-1c40595e7d02.png) No permite pulsar el pequeño botón rojo para resetear los usos.

El autor del sistema me ha avisado de que ha retocado los tamaños de estos textos. Si estás en v10 y puedes actualizar a la última versión del sistema y probarlo, me dices.
